changelog:
  categories:
    - title: '🚀 New Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'fix'
        - 'bugfix'
    - title: '📝 Documentation'
      labels:
        - 'documentation'
        - 'docs'
    - title: '🏠 Housekeeping'
      labels:
        - 'chore'
        - 'ci'
        - 'build'
        - 'test'
    - title: '⬆️ Dependency Updates'
      labels:
        - 'dependencies'
    - title: 'Other Changes'
      labels:
        - '*'
